// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Yotei.Api.Data;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(YoteiDbContext))]
    [Migration("20260130173604_AddReviewNodeQuestions")]
    partial class AddReviewNodeQuestions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Yotei.Api.Models.ChangeNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AddedLines")
                        .HasColumnType("integer");

                    b.Property<Guid>("ChangeTreeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeType")
                        .HasColumnType("text");

                    b.Property<int>("DeletedLines")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.Property<string>("RawDiffRef")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChangeTreeId");

                    b.HasIndex("ParentId");

                    b.ToTable("ChangeNodes");
                });

            modelBuilder.Entity("Yotei.Api.Models.ChangeNodeExplanation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChangeNodeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChangeNodeId");

                    b.ToTable("ChangeNodeExplanations");
                });

            modelBuilder.Entity("Yotei.Api.Models.ChangeTree", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PullRequestSnapshotId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PullRequestSnapshotId")
                        .IsUnique();

                    b.ToTable("ChangeTrees");
                });

            modelBuilder.Entity("Yotei.Api.Models.FileChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AddedLines")
                        .HasColumnType("integer");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeletedLines")
                        .HasColumnType("integer");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PullRequestSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<string>("RawDiffRef")
                        .HasColumnType("text");

                    b.Property<string>("RawDiffText")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PullRequestSnapshotId", "Path");

                    b.ToTable("FileChanges");
                });

            modelBuilder.Entity("Yotei.Api.Models.IngestionCursor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LastHeadSha")
                        .HasColumnType("text");

                    b.Property<int?>("LastPrNumber")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId")
                        .IsUnique();

                    b.ToTable("IngestionCursors");
                });

            modelBuilder.Entity("Yotei.Api.Models.PullRequestSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaseSha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HeadSha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PrNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "PrNumber", "HeadSha")
                        .IsUnique();

                    b.ToTable("PullRequestSnapshots");
                });

            modelBuilder.Entity("Yotei.Api.Models.RawDiffBlob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiffText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PullRequestSnapshotId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PullRequestSnapshotId", "Path")
                        .IsUnique();

                    b.ToTable("RawDiffBlobs");
                });

            modelBuilder.Entity("Yotei.Api.Models.Repository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Owner", "Name")
                        .IsUnique();

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("Yotei.Api.Models.ReviewNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<string>>("Evidence")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.Property<Guid>("ReviewSessionId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("RiskTags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("ReviewSessionId");

                    b.ToTable("ReviewNodes");
                });

            modelBuilder.Entity("Yotei.Api.Models.ReviewNodeBehaviourSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BehaviourChange")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReviewNodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReviewerFocus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReviewNodeId")
                        .IsUnique();

                    b.ToTable("ReviewNodeBehaviourSummaries");
                });

            modelBuilder.Entity("Yotei.Api.Models.ReviewNodeChecklist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<string>>("Items")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid>("ReviewNodeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReviewNodeId")
                        .IsUnique();

                    b.ToTable("ReviewNodeChecklists");
                });

            modelBuilder.Entity("Yotei.Api.Models.ReviewNodeExplanation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ReviewNodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReviewNodeId")
                        .IsUnique();

                    b.ToTable("ReviewNodeExplanations");
                });

            modelBuilder.Entity("Yotei.Api.Models.ReviewNodeQuestions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<string>>("Items")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid>("ReviewNodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReviewNodeId")
                        .IsUnique();

                    b.ToTable("ReviewNodeQuestions");
                });

            modelBuilder.Entity("Yotei.Api.Models.ReviewSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PullRequestSnapshotId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PullRequestSnapshotId")
                        .IsUnique();

                    b.ToTable("ReviewSessions");
                });

            modelBuilder.Entity("Yotei.Api.Models.ReviewSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChangedFilesCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeletedFilesCount")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("EntryPoints")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("ModifiedFilesCount")
                        .HasColumnType("integer");

                    b.Property<int>("NewFilesCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("ReviewSessionId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("RiskTags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("SideEffects")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("TopPaths")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("ReviewSessionId")
                        .IsUnique();

                    b.ToTable("ReviewSummaries");
                });

            modelBuilder.Entity("Yotei.Api.Models.ChangeNode", b =>
                {
                    b.HasOne("Yotei.Api.Models.ChangeTree", "ChangeTree")
                        .WithMany("Nodes")
                        .HasForeignKey("ChangeTreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Yotei.Api.Models.ChangeNode", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("ChangeTree");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Yotei.Api.Models.ChangeNodeExplanation", b =>
                {
                    b.HasOne("Yotei.Api.Models.ChangeNode", "ChangeNode")
                        .WithMany()
                        .HasForeignKey("ChangeNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangeNode");
                });

            modelBuilder.Entity("Yotei.Api.Models.ChangeTree", b =>
                {
                    b.HasOne("Yotei.Api.Models.PullRequestSnapshot", "PullRequestSnapshot")
                        .WithMany()
                        .HasForeignKey("PullRequestSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PullRequestSnapshot");
                });

            modelBuilder.Entity("Yotei.Api.Models.FileChange", b =>
                {
                    b.HasOne("Yotei.Api.Models.PullRequestSnapshot", "PullRequestSnapshot")
                        .WithMany("FileChanges")
                        .HasForeignKey("PullRequestSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PullRequestSnapshot");
                });

            modelBuilder.Entity("Yotei.Api.Models.IngestionCursor", b =>
                {
                    b.HasOne("Yotei.Api.Models.Repository", "Repository")
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("Yotei.Api.Models.PullRequestSnapshot", b =>
                {
                    b.HasOne("Yotei.Api.Models.Repository", "Repository")
                        .WithMany("PullRequestSnapshots")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("Yotei.Api.Models.RawDiffBlob", b =>
                {
                    b.HasOne("Yotei.Api.Models.PullRequestSnapshot", "PullRequestSnapshot")
                        .WithMany()
                        .HasForeignKey("PullRequestSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PullRequestSnapshot");
                });

            modelBuilder.Entity("Yotei.Api.Models.ReviewNode", b =>
                {
                    b.HasOne("Yotei.Api.Models.ReviewNode", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.HasOne("Yotei.Api.Models.ReviewSession", "ReviewSession")
                        .WithMany("Nodes")
                        .HasForeignKey("ReviewSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("ReviewSession");
                });

            modelBuilder.Entity("Yotei.Api.Models.ReviewNodeBehaviourSummary", b =>
                {
                    b.HasOne("Yotei.Api.Models.ReviewNode", "ReviewNode")
                        .WithMany()
                        .HasForeignKey("ReviewNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReviewNode");
                });

            modelBuilder.Entity("Yotei.Api.Models.ReviewNodeChecklist", b =>
                {
                    b.HasOne("Yotei.Api.Models.ReviewNode", "ReviewNode")
                        .WithMany()
                        .HasForeignKey("ReviewNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReviewNode");
                });

            modelBuilder.Entity("Yotei.Api.Models.ReviewNodeExplanation", b =>
                {
                    b.HasOne("Yotei.Api.Models.ReviewNode", "ReviewNode")
                        .WithMany()
                        .HasForeignKey("ReviewNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReviewNode");
                });

            modelBuilder.Entity("Yotei.Api.Models.ReviewNodeQuestions", b =>
                {
                    b.HasOne("Yotei.Api.Models.ReviewNode", "ReviewNode")
                        .WithMany()
                        .HasForeignKey("ReviewNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReviewNode");
                });

            modelBuilder.Entity("Yotei.Api.Models.ReviewSession", b =>
                {
                    b.HasOne("Yotei.Api.Models.PullRequestSnapshot", "PullRequestSnapshot")
                        .WithMany()
                        .HasForeignKey("PullRequestSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PullRequestSnapshot");
                });

            modelBuilder.Entity("Yotei.Api.Models.ReviewSummary", b =>
                {
                    b.HasOne("Yotei.Api.Models.ReviewSession", "ReviewSession")
                        .WithOne("Summary")
                        .HasForeignKey("Yotei.Api.Models.ReviewSummary", "ReviewSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReviewSession");
                });

            modelBuilder.Entity("Yotei.Api.Models.ChangeTree", b =>
                {
                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("Yotei.Api.Models.PullRequestSnapshot", b =>
                {
                    b.Navigation("FileChanges");
                });

            modelBuilder.Entity("Yotei.Api.Models.Repository", b =>
                {
                    b.Navigation("PullRequestSnapshots");
                });

            modelBuilder.Entity("Yotei.Api.Models.ReviewNode", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Yotei.Api.Models.ReviewSession", b =>
                {
                    b.Navigation("Nodes");

                    b.Navigation("Summary");
                });
#pragma warning restore 612, 618
        }
    }
}
